name: Deploy Fake
on:
  workflow_call:
jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no ambiente
        run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_ENTREGA }}"
      - name: Curl Deploy
        run: "curl -X https://webhook.site/1a041357-45f3-4ad1-98a5-95da5320ae4d -d '{ ambiente: ${{ secrets.AMBIENTE_ENTREGA }}}'"
